### Library Installs############################################################
library(shiny)
#devtools::install_github("pearce790/rankrate")
library(rankrate)
library(ggplot2)
library(reshape2)
library(toOrdinal)
library(highcharter)
library(shinycssloaders)
library(plotly)
library(DT)
library(ggrepel)
library(latexpdf)
library(knitr)
library(shinyalert)
library(ggfun)
library(ggimage)
library(ggplotify)
library(gridGraphics)
library(hexSticker)
library(hexbin)
library(magick)
library(showtext)
library(showtextdb)

# Define server logic
function(input, output, session) {
    source("server/dataServer.R",local=T)
    source("server/MB.R",local=T)
    source("server/dataUpload.R", local=T)
    source("server/Report.R", local=T)
}
